# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cinyo\Desktop\pys\MazeSolver\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(846, 546)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        main.setFont(font)
        self.pushButton_generateMaze = QtWidgets.QPushButton(main)
        self.pushButton_generateMaze.setGeometry(QtCore.QRect(570, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pushButton_generateMaze.setFont(font)
        self.pushButton_generateMaze.setObjectName("pushButton_generateMaze")
        self.label = QtWidgets.QLabel(main)
        self.label.setGeometry(QtCore.QRect(560, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox_mazeSize = QtWidgets.QComboBox(main)
        self.comboBox_mazeSize.setGeometry(QtCore.QRect(700, 110, 91, 29))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.comboBox_mazeSize.setFont(font)
        self.comboBox_mazeSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_mazeSize.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_mazeSize.setObjectName("comboBox_mazeSize")
        self.comboBox_mazeSize.addItem("")
        self.comboBox_mazeSize.addItem("")
        self.comboBox_mazeSize.addItem("")
        self.comboBox_mazeSize.addItem("")
        self.comboBox_mazeSize.addItem("")
        self.pushButton_solveMaze = QtWidgets.QPushButton(main)
        self.pushButton_solveMaze.setGeometry(QtCore.QRect(700, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pushButton_solveMaze.setFont(font)
        self.pushButton_solveMaze.setObjectName("pushButton_solveMaze")
        self.widget = QtWidgets.QWidget(main)
        self.widget.setGeometry(QtCore.QRect(30, 30, 481, 481))
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(main)
        self.label_2.setGeometry(QtCore.QRect(580, 290, 91, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(main)
        self.label_3.setGeometry(QtCore.QRect(580, 340, 91, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(main)
        self.label_4.setGeometry(QtCore.QRect(580, 390, 91, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(main)
        self.label_5.setGeometry(QtCore.QRect(580, 440, 91, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_epoch = QtWidgets.QLabel(main)
        self.label_epoch.setGeometry(QtCore.QRect(700, 290, 101, 31))
        self.label_epoch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_epoch.setObjectName("label_epoch")
        self.label_loss = QtWidgets.QLabel(main)
        self.label_loss.setGeometry(QtCore.QRect(700, 340, 101, 31))
        self.label_loss.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loss.setObjectName("label_loss")
        self.label_winRate = QtWidgets.QLabel(main)
        self.label_winRate.setGeometry(QtCore.QRect(700, 390, 101, 31))
        self.label_winRate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_winRate.setObjectName("label_winRate")
        self.label_time = QtWidgets.QLabel(main)
        self.label_time.setGeometry(QtCore.QRect(680, 440, 141, 31))
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "MazeSolver"))
        self.pushButton_generateMaze.setText(_translate("main", "生成迷宫"))
        self.label.setText(_translate("main", "迷宫大小："))
        self.comboBox_mazeSize.setCurrentText(_translate("main", "4"))
        self.comboBox_mazeSize.setItemText(0, _translate("main", "4"))
        self.comboBox_mazeSize.setItemText(1, _translate("main", "5"))
        self.comboBox_mazeSize.setItemText(2, _translate("main", "6"))
        self.comboBox_mazeSize.setItemText(3, _translate("main", "7"))
        self.comboBox_mazeSize.setItemText(4, _translate("main", "8"))
        self.pushButton_solveMaze.setText(_translate("main", "开始训练"))
        self.label_2.setText(_translate("main", "Epoch："))
        self.label_3.setText(_translate("main", "Loss："))
        self.label_4.setText(_translate("main", "Win Rate:"))
        self.label_5.setText(_translate("main", "Time:"))
        self.label_epoch.setText(_translate("main", "0"))
        self.label_loss.setText(_translate("main", "0"))
        self.label_winRate.setText(_translate("main", "0"))
        self.label_time.setText(_translate("main", "0"))
